name: CD
on:
  push:
    branches: 
      - "main"

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: 
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.REACT_APP_REPO }}
        run: bun install --frozen-lockfile

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.REACT_APP_REPO }}
