name: CD
on:
  push:
    branches:
      - "main"

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch repository data
        run: |
          curl -H "Authorization: Bearer ${{ secrets.REACT_APP_APIKEY }}" \
          https://api.github.com/users/cheezecakee/repos > repo-data.json

      - name: Save data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo-data
          path: ./src/data/repo-data.json

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: fetch-data
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download data artifact
        uses: actions/download-artifact@v3
        with:
          name: repo-data
          path: ./src/data/repo-data.json
          overwrite: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build website
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

