name: CD
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build website
        run: bun run build

      - name: Verify GitHub API access
        run: |
          curl -v --request GET \
          --url https://api.github.com/users/cheezecakee/repos \
          --header "Authorization: Bearer ${{ secrets.REACT_APP_APIKEY }}" \
          --header "Content-Type: application/json"

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

