
name: CD
on:
  push:
    branches:
      - "main"

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch repository data
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_REPO }}
        run: |
          repos=$(curl -H "Authorization: Bearer ${{ secrets.REACT_APP_REPO }}" https://api.github.com/users/cheezecakee/repos)
          echo "$repos" > repo-data.json
          
          # Initialize an empty array to store updated repo data with languages
          echo "[]" > src/data/repo-data.json

          # Loop through each repo and fetch its languages
          for repo in $(echo "$repos" | jq -c '.[]'); do
            repo_name=$(echo $repo | jq -r '.name')
            languages_url=$(echo $repo | jq -r '.languages_url')
            languages=$(curl -H "Authorization: Bearer ${{ secrets.REACT_APP_REPO }}" $languages_url)
            repo_with_languages=$(echo $repo | jq --argjson languages "$languages" '. + {languages: $languages}')
            
            # Append the updated repo data to repo-data.json
            jq ". += [$repo_with_languages]" src/data/repo-data.json > src/data/tmp.json && mv src/data/tmp.json src/data/repo-data.json
          done

      - name: Display fetched data
        run: cat src/data/repo-data.json

      - name: Save data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo-data
          path: src/data/repo-data.json

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: fetch-data
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Remove existing repo-data.json if exists
        run: rm -f ./src/data/repo-data.json

      - name: Download data artifact
        uses: actions/download-artifact@v3
        with:
          name: repo-data
          path: ./src/data

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build website
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with



