name: CD
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
    name: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
        run: bun install

      - name: Build
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

