name: CD
on:
  push:
    branches: 
      - "main"

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: 
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.REACT_APP_REPO }}
        run: bun install --frozen-lockfile

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build 
