name: CD
on:
  push:
    branches: 
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
        run: bun install

      - name: Build
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
        run: bun run build

      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build

